// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/26 21:36:49
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/demo/maomao4/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/demo/maomao4/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/demo/maomao4/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/demo/maomao4/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/demo/maomao4/plugins/**/*.{js,ts,mjs}","D:/demo/maomao4/composables/**/*.{js,ts,mjs}","D:/demo/maomao4/utils/**/*.{js,ts,mjs}","D:/demo/maomao4/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/demo/maomao4/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/demo/maomao4/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/demo/maomao4/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;